config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :lawnmowers do
    resources :bookings, except: [:index, :edit, :update]
    resources :reviews
  end
  resources :bookings, only: [:index]
  devise_for :users
  patch 'bookings/:id/accepted', to: 'bookings#accepted', as: 'accepted'
  patch 'bookings/:id/cancelled', to: 'bookings#cancelled', as: 'cancelled'
  patch 'bookings/:id/cancelled_user', to: 'bookings#cancelled_user', as: 'cancelled_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :lawnmower

  enum status: {
    pending: 0,
    confirmed: 1,
    cancelled: 2
  }
end

app/models/lawnmower.rb
class Lawnmower < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  validates :title, :price, :description, :speed, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title,
  against: [ :title],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :lawnmower
  belongs_to :user
  has_one_attached :photo
  validates :comment, presence: true
  validates :rating, presence: true, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  has_many :lawnmowers, dependent: :destroy
  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :index
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address, :photo, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:address, :photo, :name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :update, :destroy, :cancelled, :accepted, :cancelled_user]
  before_action :set_lawnmower, only: [:new, :create]

  def accepted
    @booking.confirmed!
    redirect_to bookings_path
  end

  def cancelled
    @booking.cancelled!
    redirect_to bookings_path
  end

  def cancelled_user
    @booking.cancelled!
    redirect_to lawnmower_booking_path(@booking.lawnmower, @booking)
  end

  def index
    @bookings = Booking.where(user: current_user)
    lawnmowers = Lawnmower.where(user: current_user)
    @lawnmowerbookings = Booking.select { |booking| lawnmowers.include?(booking.lawnmower)}
  end

  def show; end

  def edit; end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.lawnmower = @lawnmower
    @booking.pending!
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_lawnmower
    @lawnmower = Lawnmower.find(params[:lawnmower_id])
  end

  def booking_params
    params.require(:booking).permit(:user_id, :lawnmower_id, :booking_date, :status)
  end
end

app/controllers/lawnmowers_controller.rb
class LawnmowersController < ApplicationController
  before_action :set_lawnmower, only: [:show, :update, :destroy]

  def index
    if params[:query].present?
      @lawnmowers = Lawnmower.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @lawnmowers = Lawnmower.all
    end
  end

  def show
    @review = Review.new
  end

  def new
    @lawnmower = Lawnmower.new
  end

  def create
    @lawnmower = Lawnmower.new(lawnmower_params)
    @lawnmower.user = current_user
    if @lawnmower.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @lawnmower.update(lawnmower_params)
    redirect_to lawmower_path(@lawnmower)
  end

  def destroy
    @lawnmower.destroy
    redirect_to lawnmowers_path, status: :see_other
  end

  private

  def set_lawnmower
    @lawnmower = Lawnmower.find(params[:id])
  end

  def lawnmower_params
    params.require(:lawnmower).permit(:title, :price, :description, :speed, :user_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    if params[:query].present?
      @lawnmowers = Lawnmower.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @lawnmowers = Lawnmower.all
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :update, :destroy]
  before_action :set_lawnmower, only: [:create, :destroy]

  def create
    @review = Review.new(review_params)
    @review.lawnmower = @lawnmower
    @review.user = current_user
    if @review.save
      redirect_to lawnmower_path(@lawnmower)
    else
      render 'lawnmowers/show', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  def destroy
    @review.destroy
    redirect_to lawnmower_path(@lawnmower), status: :see_other
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_lawnmower
    @lawnmower = Lawnmower.find(params[:lawnmower_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating, :photo, :user_id, :lawnmower_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container d-flex justify-content-around booking-margin">
  <div>
    <% if @bookings.empty? %>
      <div class="my-booking-container">
        <div class="my-booking-card align-items-center">
          <strong><h1>My Bookings</h1></strong>
            <h4>You currently have no bookings!</h4>
              <div class="btn btn-danger">
                <%= link_to 'Find a Mawnlower', root_path, class:'text-info' %>
              </div>
        </div>
      </div>
    <% else %>
      <div class="my-booking-container">
      <div class="request-card">
          <strong><h1>My Bookings</h1></strong>
        </div>
        <% @bookings.reverse.each do |booking| %>
          <div class="my-booking-card">
            <p>Title: <%= booking.lawnmower.title.capitalize %></p>
            <p>Price: <%= booking.lawnmower.price %>$</p>
            <p>Requested on: <%= booking.booking_date%></p>
            <p><%= booking.user.name %>, <%= booking.user.address %></p>
              <% if booking.pending? %>
                <p><%= booking.lawnmower.user.name %> has received your request.</p>
                <p class="text-warning">Status: Order pending</p>
              <% elsif booking.confirmed? %>
                <p class="text-success">Status: Order confirmed</p>
              <% else %>
                <p class="text-danger">Status: Order cancelled</p>
              <% end %>
            <small><%= link_to 'View Booking', lawnmower_booking_path(booking.lawnmower, booking)%></small>
            <small><%= link_to 'Delete Booking', lawnmower_booking_path(booking.lawnmower, booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'text-danger' %></small>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="my-confirmed-container">
        <% if @lawnmowerbookings.empty? %>
          <div class="my-booking-container">
            <div class="my-booking-card align-items-center">
              <strong><h1>My Requests</h1></strong>
              <h4>Currently no bookings!</h4>
                <div class="btn btn-danger">
                  <%= link_to 'Create more offers', new_lawnmower_path , class:'text-info' %>
                </div>
            </div>
          </div>
        <% else %>
        <div>
        <div class="request-card">
          <strong><h1>My Requests</h1></strong>
        </div>
          <% @lawnmowerbookings.reverse.each do |booking| %>
            <div class="my-booking-card">
              <p><%= booking.lawnmower.title.capitalize %>: <%= booking.lawnmower.price %>$</p>
              <p>Requested on: <%= booking.booking_date%></p>
              <p>Address: <%= booking.user.address %></p>
              <p>By: <%= booking.user.name %></p>
                <% if booking.pending? %>
                  <p><%= booking.lawnmower.user.name %> has received your request.</p>
                  <p>Status: Order pending</p>
                <% elsif booking.confirmed? %>
                  <p class="text-success">Status: Order confirmed</p>
                <% else %>
                  <p class="text-danger">Status: Order cancelled</p>
                <% end %>
                <% if booking.pending? == false  %>
                  <p></p>
                <% else %>
                  <%= link_to 'Accept', accepted_path(booking), data: { turbo_method: :patch} %>
                  <%= link_to 'Deny', cancelled_path(booking), data: { turbo_method: :patch}, class: 'text-danger' %>
                <% end %>
              </div>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add an offer</h3>
        <%= simple_form_for [@lawnmower, @booking] do |f| %>
          <%= f.input :booking_date, as: :date, html5: true, class: 'btn btn-flat' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="show-booking-container">
  <div class="img-booking">
    <%= cl_image_tag @booking.lawnmower.photo.key %>
  </div>
  <div class="booking-info">
    <div class="details">
      <h2><%= @booking.lawnmower.title %></h2>
      <p>Decription: <%= @booking.lawnmower.description %></p>
      <p>Speed: <%= @booking.lawnmower.speed %></p>
    </div>
    <div>
      <h3>Booking Details</h3>
      <p>Price: <%= @booking.lawnmower.price %>€</p>
      <p>Booking made on: <%= @booking.booking_date%></p>
      <p>By: <%= @booking.user.name %> ,  Address: <%= @booking.user.address %></p>
      <% if @booking.pending? %>
        <p><%= @booking.lawnmower.user.name %> has received your request.</p>
        <p>Status: Order pending</p>
      <% elsif @booking.confirmed? %>
        <p>Status: Order confirmed</p>
      <% else %>
        <p>Status: Order cancelled</p>
      <% end %></div>
      <%= link_to 'Cancel Order', cancelled_user_path(@booking), data: { turbo_method: :patch}, class: 'text-danger' %>
    </div>
  </div>
</div>

app/views/lawnmowers/index.html.erb
<h1 class="text-center">My MawnLowers</h1>
<%= form_with url: lawnmowers_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find your MawnLower"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
<div class="row my-2">
  <% if @lawnmowers.empty? %>
    <p>There are no MawnLowers</p>
    <% else %>
    <% @lawnmowers.each do |lawnmower| %>
      <% if lawnmower.user == current_user %>
        <div class="col-12 col-sm-4 mb-4" data-aos="zoom-in">
          <div class="bg-white rounded shadow h-100">
            <div class="p-3 rounded-bottom d-flex flex-column">
              <%= link_to lawnmower_path(lawnmower), data: { turbo_method: :get } do %>
              <strong><%= lawnmower.title.capitalize %> <span class="text-muted font-weight-normal">• <%= lawnmower.price %> <i class="fas fa-dollar"></i></span></strong>
                <%= cl_image_tag lawnmower.photo.key, style: "width: 100%; height:230px;", crop: :fill %>
              <% end %>
              <small class="text-muted"><%= lawnmower.description %></small>
              <div class="d-flex align-items-end justify-content-between pt-4">
                <div>
                  <span>Speed:  </span><small class="flex-grow-1"><%= lawnmower.speed %></small>
                  <span>By: <%= lawnmower.user.name%></span>
                </div>
                <small class="text-right flex-shrink-0">
                <% if user_signed_in? %>
                    <%= link_to 'View Offer', lawnmower_path(lawnmower), data: { turbo_method: :get } %></small>
                      <% if lawnmower.user == current_user %>
                        <%= link_to 'Delete lawnmower', lawnmower_path(lawnmower), data: { turbo_method: :delete, confirm: "Are you sure you want to remove #{lawnmower.title}"}, class: 'text-danger' %></small>
                      <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  </div>

app/views/lawnmowers/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow mt-5">
        <h3>Add an offer</h3>
        <%= simple_form_for @lawnmower do |f| %>
          <%= f.input :title, placeholder: 'Grandma With dentures' %>
          <%= f.input :price, placeholder: '200$' %>
          <%= f.input :description, placeholder: 'Its chomping time' %>
          <%= f.input :speed, placeholder: '1 to 5' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lawnmowers/show.html.erb
  <% @sum = 0 %>
  <% @lawnmower.reviews.each do |review| %>
  <%   @sum += review.rating %>
  <% end %>
<div>
  <div class="show-page-container">
    <div>
      <div class="img">
        <%= cl_image_tag @lawnmower.photo.key, style: "width: 100%" %>
      </div>
      <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Reviews(<%= @lawnmower.reviews.count %>)
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <div class="card-reviews">
                <div>
                  <% if @lawnmower.reviews.empty? %>
                    <p>Be the first to add a review!</p>
                  <% else %>
                    <h3> Reviews </h3>
                    <% @lawnmower.reviews.each do |review| %>
                    <div class="review-info">
                      <p><%= review.rating %><i class="fas fa-star star-yellow"></i></p>
                      <p><%= review.comment %></p>
                      <p>Review by: <%= review.user.name %></p>
                      <% if review.user == current_user %>
                        <small><%= link_to 'Delete Review', lawnmower_review_path(review.lawnmower, review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'text-danger' %></small>
                      <% end %>
                    </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="product-info">
      <div class="card-product-infos">
        <h2><%= @lawnmower.title %> <%= @sum.to_f/@lawnmower.reviews.count %><i class="fas fa-star star-yellow"></i></h2>
        <p>Decription: <%= @lawnmower.description %></p>
        <p>Speed: <%= @lawnmower.speed %></p>
      </div>
      <div class="pricing-info">
        <h3>Price: <%= @lawnmower.price %>€</h3>
        <%= link_to "Book", new_lawnmower_booking_path(@lawnmower), class: "btn btn-outline-info" %>
      </div>
      <div class="review-form">
        <h3>Add your own review!</h3>
        <%= simple_form_for([@lawnmower, @review]) do |f| %>
          <%= f.input :comment, placeholder: 'Add your review here!' %>
          <%= f.input :rating, placeholder: 'Rate me!' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: "btn btn-outline-info" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lawnmowers/update.html.erb
<%= simple_form_for(lawnmower) do |f| %>
  <%= f.input :title %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :speed %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mawnlower</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="heroimage" style="background-image: url('https://images.unsplash.com/photo-1533460004989-cef01064af7e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Z3Jhc3N8ZW58MHx8MHx8&w=1000&q=80'); height: 70vh;">
  <div class="herogradient w-100 h-100 d-flex justify-content-center align-items-center">
    <div>
      <h1 class="text-white">MawnLowers</h1>
      <div class=" d-flex justify-content-center">
        <div class="searchbar w-50">
          <%= form_with url: root_path , method: :get, class:"d-flex justify-content-center" do %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control search-input",
            placeholder: "Find your Mawnlower"%>
            <%= submit_tag "🔍", class:"btn search-btn"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center">
</div>
<div class="row my-2">
<div class="row my-2">
  <% if @lawnmowers.empty? %>
    <p>There are no MawnLowers</p>
    <% else %>
    <% @lawnmowers.each do |lawnmower| %>
      <% if lawnmower.user != current_user %>
        <div class="col-12 col-sm-4 mb-4" data-aos="zoom-in">
          <div class="bg-white rounded shadow h-100">
            <div class="p-3 rounded-bottom d-flex flex-column">
              <%= link_to lawnmower_path(lawnmower), data: { turbo_method: :get } do %>
              <strong><%= lawnmower.title.capitalize %> <span class="text-muted font-weight-normal">• <%= lawnmower.price %> <i class="fas fa-dollar"></i></span></strong>
                  <%= cl_image_tag lawnmower.photo.key, style: "width: 100%; height:230px;", crop: :fill %>
              <% end %>
              <small class="text-muted"><%= lawnmower.description %></small>
              <div class="d-flex align-items-end justify-content-between pt-4">
                <div>
                  <span>Speed:  </span><small class="flex-grow-1"><%= lawnmower.speed %></small>
                  <span>By: <%= lawnmower.user.name%></span>
                </div>
                <small class="text-right flex-shrink-0">
                <% if user_signed_in? %>
                    <%= link_to 'View Offer', lawnmower_path(lawnmower), data: { turbo_method: :get } %></small>
                      <% if lawnmower.user == current_user %>
                        <%= link_to 'Delete lawnmower', lawnmower_path(lawnmower), data: { turbo_method: :delete, confirm: "Are you sure you want to remove #{lawnmower.title}"}, class: 'text-danger' %></small>
                      <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to '/', class: "navbar-brand" do %>
      <%= image_tag "mawnlower_logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Create Offer", new_lawnmower_path , class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "noprofile_img.png", height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Offers", lawnmowers_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete, confirm: "Are you sure you want to logout?"}, class: 'text-danger dropdown-item' %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>